version: '3.9'

services:
  mongodb-prod:
    image: mongo:latest
    container_name: mongodb-prod
    restart: unless-stopped
    env_file:
      - ./.env.db
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    volumes:
      - mongodb_data_container:/data/db
      - type: bind
        source: ../init-mongo.sh
        target: /docker-entrypoint-initdb.d/init-mongo.sh
        read_only: true
    networks:
      - production

  rabbitmq-prod:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rmq_data_container:/var/lib/rabbitmq/
    env_file:
      - ./.env.rmq
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    networks:
      - production

  redis-discord-bot-prod:
    image: redis:7.0.11
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 7378:6379
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    volumes:
      - type: bind
        source: ./redis/discordBot.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    networks:
      - production

  redis-discord-analyzer-prod:
    image: redis:7.0.11
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 8378:6379
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    volumes:
      - type: bind
        source: ./redis/discordAnalyzer.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    networks:
      - production

  neo4j-prod:
    image: neo4j:4.4.19
    restart: unless-stopped
    ports:
      - 17474:7474
      - 17687:7687
    env_file:
      - ./.env.neo4j
    volumes:
      - neo4j_conf_container:/var/lib/neo4j/conf
      - neo4j_data_container:/data
      - neo4j_import_container:/import
      - neo4j_plugins_container:/plugins
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - production

  tc-server-comm-prod:
    build:
      context: ../../tc-serverComm
      dockerfile: Dockerfile
      tags:
        - tc-server-comm:${VERSION:-latest}
    restart: unless-stopped
    environment:
      PORT: $PORT
    ports:
      - $HOST:$PORT:$PORT
    env_file:
      - ./.env.proc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      - mongodb-prod
      - neo4j-prod
      - rabbitmq-prod
    networks:
      - production

  tc-discord-bot-prod:
    build:
      context: ../../tc-discordBot
      target: prod
      dockerfile: Dockerfile
      tags:
        - tc-discord-bot:${VERSION:-latest}
    restart: unless-stopped
    env_file:
      - ./.env.bot.proc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      - mongodb-prod
      - redis-discord-bot-prod
      - rabbitmq-prod
    networks:
      - production

  tc-discord-analyzer-server-prod:
    build:
      context: ../tc-DAOlytics-operation
      target: prod-server
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      tags:
        - tc-discord-analyzer:${VERSION:-latest}
    restart: unless-stopped
    env_file:
      - ./.env.analyzer.proc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      - redis-discord-analyzer-prod
      - rabbitmq-prod
    networks:
      - production

  tc-discord-analyzer-worker-prod:
    build:
      context: ../tc-DAOlytics-operation
      target: prod-worker
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      tags:
        - tc-discord-analyzer:${VERSION:-latest}
    restart: unless-stopped
    env_file:
      - ./.env.analyzer.proc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      - mongodb-prod
      - redis-discord-analyzer-prod
      - neo4j-prod
    networks:
      - production

volumes:
  mongodb_data_container:
  rmq_data_container:
  neo4j_data_container:
  neo4j_conf_container:
  neo4j_import_container:
  neo4j_plugins_container:

networks:
  production:
    driver: bridge
