version: '3.9'

x-sm-resources-common:
  &sm-resources-common
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 1G

x-md-resources-common:
  &md-resources-common
  deploy:
    resources:
      limits:
        cpus: '2'
        memory: 2G

x-lg-resources-common:
  &lg-resources-common
  deploy:
    resources:
      limits:
        cpus: '2'
        memory: 4G

x-logging:
  &logging
  logging:
    driver: loki
    options:
      loki-url: http://172.22.22.15:3100/loki/api/v1/push
      loki-retries: 5
      loki-batch-size: 400

x-redis-healthcheck:
  &redis-healthcheck
  healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 40s

x-rabbitmq-healthcheck:
  &rabbitmq-healthcheck
  healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 2
      start_period: 40s

x-mongodb-healthcheck:
  &mongodb-healthcheck
  healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 40s

x-neo4j-healthcheck:
  &neo4j-healthcheck
  healthcheck:
    test: ["CMD" ,"wget", "http://localhost:7474"]
    interval: 1m30s
    timeout: 10s
    retries: 2
    start_period: 40s

services:
  mongodb-prod:
    image: mongo:latest
    container_name: mongodb-prod
    restart: unless-stopped
    env_file:
      - ./.env.db
    ports:
      - 37017:27017
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    volumes:
      - mongodb_data_container:/data/db
      - type: bind
        source: ../init-mongo.sh
        target: /docker-entrypoint-initdb.d/init-mongo.sh
        read_only: true
    networks:
      - production
      - monitoring
    <<: *mongodb-healthcheck

  rabbitmq-prod:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
        - 15672:15672
    volumes:
        - rmq_data_container:/var/lib/rabbitmq/
    env_file:
      - ./.env.rmq
    networks:
      - production
      - monitoring
    <<: [*logging, *rabbitmq-healthcheck]

  redis-discord-bot-prod:
    image: redis:7.0.11
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - type: bind
        source: ./redis/discordBot.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    networks:
      - production
      - monitoring
    <<: [*logging, *redis-healthcheck]

  redis-discord-analyzer-prod:
    image: redis:7.0.11
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - type: bind
        source: ./redis/discordAnalyzer.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    networks:
      - production
      - monitoring
    <<: [*logging, *redis-healthcheck]

  neo4j-prod:
    image: neo4j:5.9.0
    restart: unless-stopped
    ports:
      - 27474:7474
      - 27687:7687
    env_file:
      - ./.env.neo4j
    volumes:
      # - neo4j_conf:/var/lib/neo4j/conf
      - neo4j_data:/data
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_server.memory.heap.initial_size=4G
      - NEO4J_server.memory.heap.max_size=8G
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    networks:
      - production
      - monitoring
    <<: [*logging, *neo4j-healthcheck]

  tc-server-comm-prod:
    build:
      context: ../../tc-serverComm
      dockerfile: Dockerfile
      tags:
        - tc-server-comm:${VERSION:-latest}
    restart: unless-stopped
    environment:
      PORT: $PORT
    ports:
      - $HOST:$PORT:$PORT
    env_file:
      - ./.env.proc
    depends_on:
      mongodb-prod:
        condition: service_healthy
      neo4j-prod:
        condition: service_healthy
      rabbitmq-prod:
        condition: service_healthy
    networks:
      - production
      - monitoring
    <<: *logging

  tc-discord-bot-prod:
    build:
      context: ../../tc-discordBot
      target: prod
      dockerfile: Dockerfile
      tags:
        - tc-discord-bot:${VERSION:-latest}
    restart: unless-stopped
    env_file:
      - ./.env.bot.proc
    depends_on:
      mongodb-prod:
        condition: service_healthy
      redis-discord-bot-prod:
        condition: service_healthy
      rabbitmq-prod:
        condition: service_healthy
    networks:
      - production
      - monitoring
    <<: [*logging, *sm-resources-common]

  discord-analyzer-server:
    image: ghcr.io/togethercrew/discord-analyzer:main
    command: python3 server.py
    restart: unless-stopped
    env_file:
      - ./.env.analyzer.proc
    depends_on:
      redis-discord-analyzer-prod:
        condition: service_healthy
      rabbitmq-prod:
        condition: service_healthy
    networks:
      - production
      - monitoring
    <<: *logging

  discord-analyzer-worker:
    image: ghcr.io/togethercrew/discord-analyzer:main
    command: python3 worker.py
    restart: unless-stopped
    env_file:
      - ./.env.analyzer.proc
    depends_on:
      mongodb-prod:
        condition: service_healthy
      redis-discord-analyzer-prod:
        condition: service_healthy
      neo4j-prod:
        condition: service_healthy
    networks:
      - production
      - monitoring
    <<: *logging

  # manual-triggers:
  #   build:
  #     context: ../../manual-triggers
  #     dockerfile: Dockerfile
  #     tags:
  #       - manual-triggers:${VERSION:-latest}
  #   env_file:
  #     - ./.env.manual-triggers
  #   depends_on:
  #     - mongodb-prod
  #     - rabbitmq-prod
  #   networks:
  #     - production
  #     - monitoring
  #   <<: *logging

volumes:
  mongodb_data_container:
  rmq_data_container:
  neo4j_data:
  neo4j_import:
  neo4j_plugins:
  neo4j_conf:
  grafana_volume:
  prometheus_volume:
  loki_volume:

networks:
  production:
    driver: bridge
  monitoring:
    name: monitoring
    external: true
