version: "3.9"

services:
  app:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    environment:
      - PORT=3000
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASS=pass
      - REDIS_QUEUE_HOST=redis
      - REDIS_QUEUE_PORT=6379
      - REDIS_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=root
      - RABBITMQ_PASS=pass
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_DB=neo4j
      - SAGA_DB_NAME=Saga
      - SAGA_DB_COLLECTION=saga
    volumes:
      - ./coverage:/project/coverage
    depends_on:
      - redis
      - mongo
      - neo4j
      - rabbitmq
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
  neo4j:
    image: "neo4j"