version: "3.9"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
  neo4j:
    image: "neo4j"
    ports:
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password