global:
  scrape_interval: 5s

scrape_configs:
- job_name: cadvisor
  static_configs:
    - targets:
      - cadvisor:8080

- job_name: node
  static_configs:
    - targets:
      - node-exporter:9100

- job_name: traefik
  static_configs:
    - targets:
      - traefik:8080

- job_name: tempo
    static_configs:
      - targets:
        - tempo:3200