version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    volumes:
      - portainer_data:/data/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tools